export const siteConfig = {
  getHeaderLinks: () => {
    const items = [
      {
        title: "How it Works",
        href: "/#how-it-works",
      },
      {
        title: "Benefits",
        href: "/#benefits",
      },
      {
        title: "Work",
        href: "/#work",
      },
      {
        title: "Pricing",
      },
      {
        title: "FAQs",
      },
      {
        title: "About",
      },
    ];

    return items;
  },

  images: {
    homebg:
      "https://framerusercontent.com/images/3hiBbgyX1cjx1RlBiJym2iLCo.png",
    aboutuspic:
      "https://images.followalice.com/LYMth03VDX1xjGGrW9WG0/407a868f99d578f7585b8f38ff7d6c33/Ours._S._Buddha_dordenma_statue_with_monks_and_tourists_in_Thimphu__Bhutan.jpg?q=80&fit=fill&f=center&w=1200&h=1200",
  },

  imageGroupOne: () => {
    const images = [
      "https://fh-sites.imgix.net/sites/3119/2019/11/28111731/Punakha-Dzong-e1574919168213.jpg?auto=compress%2Cformat&w=1200&fit=max",
      "https://www.andbeyond.com/wp-content/uploads/sites/5/padd-field-thimpu-bhutan.jpg",
      "https://img.thedailybeast.com/image/upload/c_crop,d_placeholder_euli9k,h_1688,w_3000,x_0,y_0/dpr_1.5/c_limit,w_1600/fl_lossy,q_auto/v1669904737/221130-oconnor-bhutan-hero_p5ua9c",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Paro%2C_Paro%2C_Bhutan_%288026008882%29.jpg/640px-Paro%2C_Paro%2C_Bhutan_%288026008882%29.jpg",
    ];

    return images;
  },
};

export const dzongkhags = [
  "Dagana",
  "Gasa",
  "Punakha",
  "Tsirang",
  "Wangdue Phodrang",
  "Bumthang",
  "Sarpang",
  "Trongsa",
  "Zhemgang",
  "Lhuntse",
  "Mongar",
  "Pema Gatshel",
  "Samdrup Jongkhar",
  "Trashigang",
  "Trashi Yangtse",
  "Chhukha",
  "Haa",
  "Paro",
  "Samtse",
  "Thimphu",
];

export const country_list = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua &amp; Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia &amp; Herzegovina",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Cayman Islands",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D Ivoire",
  "Croatia",
  "Cruise Ship",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "French West Indies",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyz Republic",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Pierre &amp; Miquelon",
  "Samoa",
  "San Marino",
  "Satellite",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "St Kitts &amp; Nevis",
  "St Lucia",
  "St Vincent",
  "St. Lucia",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor L'Este",
  "Togo",
  "Tonga",
  "Trinidad &amp; Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks &amp; Caicos",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (US)",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
